### ISSUE TITLE
Create a wireframe for the menu

### ISSUE THREAD

**Issue by vchelaru** [dantogno/FishStory#10]

**Comment by dantogno** [comment]
Shop menu: https://docs.google.com/drawings/d/1dBItD-wWw5TQLxUfaM9bvbVAphQqXD8_FTFiC7--xAs/

**Comment by dantogno** [comment]
Inventory menu: https://docs.google.com/drawings/d/1wf8hTtpewOiO-bV0SYsd-a-Wm0y3aWkGEv_cvsHZ6Gc/
