### ISSUE TITLE
Will replacing the rounded corner UI elements in the inventory with the decorative box used elsewhere look better?

### ISSUE THREAD

**Issue by dantogno** [dantogno/FishStory#104]
![image](https://user-images.githubusercontent.com/3150710/73012363-bb6f7f00-3ddb-11ea-8787-23d652565c94.png)

**Comment by Cabrill** [comment]
I took a stab at this one.  Let me know if you would like any additional changes, @dantogno

**Comment by dantogno** [comment]
Looks great! I think these issues are solved. I might open a new card with some final revision ideas about separate elements.
