### ISSUE TITLE
Dialog triggered via script does not show the character portrait

### ISSUE THREAD

**Issue by dantogno** [dantogno/FishStory#137]
**Repro steps**
1. Load main level
1. walk to the left until the script triggers the mayor dialog (woman in black dress)
**Results**
No portrait.
![image](https://user-images.githubusercontent.com/3150710/73227078-e3dade80-4137-11ea-84c0-edaf2086dd5e.png)
**Expected Results**
Portrait displays just like when player talks to anyone else. We might need to add a parameter to the `TryShow` function.

The code in question is in MainLevel.cs ln 292. `DialogBox.TryShow()`

**Comment by Cabrill** [comment]
You'll need to call `SetDialoguePortraitFor(NPC)` to specify which NPC is talking.
