### ISSUE TITLE
Improve clarity of fishing interaction

### ISSUE THREAD

**Issue by dantogno** [dantogno/FishStory#145]
I'm afraid people will not get it and spam buttons to start moving again, resulting in lost bait.

- [ ] We need constant motion or clear indication the player is in the fishing animation (any ideas?). The left and right version is great, it's the up and down that need improvement. Maybe we can show the fishing line in all 4 directions?

- [x] If the player cancels the fishing sequence early, we should display a notification. "You cut your bait."

**Comment by Cabrill** [comment]
@dantogno Let me know if the updated animation works.

**Comment by dantogno** [comment]
Works for me, thank you!!
