### ISSUE TITLE
Add wagons to tile sheet

### ISSUE THREAD

**Issue by dantogno** [dantogno/FishStory#17]
- [ ] ![wagonshseeta_1](https://user-images.githubusercontent.com/3150710/71609684-0df8ab00-2b50-11ea-8967-65e0dbc51647.png)

- [ ] ![wagonshseetb_1](https://user-images.githubusercontent.com/3150710/71609685-0f29d800-2b50-11ea-964a-fdfa27abebbf.png)

**Comment by Cabrill** [comment]
Done.  Top-right corner.
