### ISSUE TITLE
Add tiles for other brick building color

### ISSUE THREAD

**Issue by dantogno** [dantogno/FishStory#19]
In this image, you can see the tiles for a brick building I used.
![image](https://user-images.githubusercontent.com/3150710/71629894-98c7bd00-2bc5-11ea-99ed-316bf035135c.png)

There are color variations, but they are missing a couple of tiles needed to build the full building. I think these tiles can be added by taking chunks from other tiles, as in this image:
![image](https://user-images.githubusercontent.com/3150710/71629987-328f6a00-2bc6-11ea-9512-d77d11a7485b.png)

Can you try to add these tiles for one of the lighter color variations?

**Comment by Cabrill** [comment]
Would it be alright to just lighten the existing brick building tiles to match?
![image](https://user-images.githubusercontent.com/2907579/71655846-bd1eb900-2ced-11ea-9153-dc2b03cabb84.png)
Or did you want to use both light & dark versions?

**Comment by dantogno** [comment]
@Cabrill I would like two colors of the building, but this might be a smart way to get it?

**Comment by Cabrill** [comment]
There should be two colors now.  Please close this when confirmed that they work for your intentions, @dantogno
