### ISSUE TITLE
Support links with alternative text than the passage name

### ISSUE THREAD

**Issue by dantogno** [dantogno/FishStory#20]
In twine for links, you can create alternative text to show the user than the name of the passage that you're linking to.

This is useful for having multiple dialog options all link to one passage, for example.

When alternative text is provided in a link, show that and not the passage name. Right now we are showing both: 
![image](https://user-images.githubusercontent.com/3150710/71630214-6f0f9580-2bc7-11ea-9ee7-40be53fcf028.png)

I would prefer it just said "I'm here to Fish", "Fishing festival?" and "..." in this example.

You can see this in-game by talking to the guy on the dock once the game loads.

**Comment by dantogno** [comment]
@vchelaru actually, if you choose a dialog option with alternative text like this, it crashes the game because it says the passage name is null!

**Comment by Cabrill** [comment]
I think my changes yesterday fixed this.  Can you confirm and close the issue, @dantogno ?
