### ISSUE TITLE
Player art

### ISSUE THREAD

**Issue by dantogno** [dantogno/FishStory#3]
- [x] Walk
- [x] Idle
- [x] Fish

**Comment by Cabrill** [comment]
Added Idle, Fish, WalkUp, WalkDown, WalkLeft, and WalkRight.
https://github.com/dantogno/FishStory/commit/e38a94cb24abebc8127fd94d7cb2c0be51c4cfde

**Comment by dantogno** [comment]
We can use this guy for an NPC, but for the player, we'd like to use this one if possible: 
![image](https://user-images.githubusercontent.com/3150710/71525284-0068ca00-289f-11ea-8e33-fddd9d7580f0.png)

Should be in the tilesheet

**Comment by Cabrill** [comment]
@dantogno The player character has been replaced with the one above.
