### ISSUE TITLE
Are there animated flag sprites somewhere in the asset dump? If we can find them, and they fit the stuff we're using, I will use them!

### ISSUE THREAD

**Issue by dantogno** [dantogno/FishStory#32]

**Comment by Cabrill** [comment]
Added animated blue/white flags, with and without sticks.
![flagpoleless_1](https://user-images.githubusercontent.com/2907579/71771033-ca07fc00-2ee9-11ea-84c5-9492ea08c9db.png)
![flagpoles_1](https://user-images.githubusercontent.com/2907579/71771035-cbd1bf80-2ee9-11ea-91b1-e6bbdc763ccf.png)
