### ISSUE TITLE
Low priority: add transparent background to stall tiles

### ISSUE THREAD

**Issue by dantogno** [dantogno/FishStory#36]
![image](https://user-images.githubusercontent.com/3150710/71770937-1149b900-2ef9-11ea-9d96-413b15f3cc92.png)
☝️  These should match these 👇 
 
![image](https://user-images.githubusercontent.com/3150710/71770948-34746880-2ef9-11ea-9e9d-8f0d30f13944.png)

**Comment by Cabrill** [comment]
Done.
