### ISSUE TITLE
Blue flag needs to be an animated entity I can place (this way I can place it anywhere, not just on the tile grid)

### ISSUE THREAD

**Issue by dantogno** [dantogno/FishStory#37]
![image](https://user-images.githubusercontent.com/3150710/71839664-513ba800-3081-11ea-8b3d-2cd4b9698e51.png)

**Comment by Cabrill** [comment]
I added a PropObject entity class, with an animated flag that can be placed as an object in Tiled with whatever collision object seems necessary.

**Comment by Cabrill** [comment]
Let me know if this worked, @dantogno

**Comment by dantogno** [comment]
@Cabrill It doesn't seem to be working, maybe I don't have it setup correctly:
![image](https://user-images.githubusercontent.com/3150710/71915408-4ea08780-3141-11ea-9e18-6fb269339ef9.png)

Here is how it appears in game:
![image](https://user-images.githubusercontent.com/3150710/71915471-6d9f1980-3141-11ea-840b-9a42a9641393.png)
