### ISSUE TITLE
Identification NPC must identify fish before they can be sold to the fishmongers, except when selling to a special black market NPC vendor. The identification is conveyed as some environmental / bureaucratic tax measure, but really it is used by the town elder / priest to read omens from the lake based on what's coming out of it.

### ISSUE THREAD

**Issue by dantogno** [dantogno/FishStory#38]
This would require
- A new column in the item csv for unidentified name (if there is no value provided for unidentified name, it just starts out identified)
- A way for the fish monger vendor to tell the player you can't sell the fish unless it's identified
- A way to talk to the ID NPC who offers an option to ID the fish (all of them at once).

**Comment by vchelaru** [comment]
If a user has fish to identify, the user asks"Do you want to identify your fish?" 

If the user says "yes" then a notification tells them that they identified fish. There is no cost.

If the user says "no" then nothing happens.

We need special stores:

Dave says:

I think we should just have the black market guy who buys everything
And the fish monger who only buys identified fish
and the bait people only sell

Black market guy pays less than legit fishmonger, regardless of identification status.

Therefore, identification just lets you sell to fishmonger for more.
