### ISSUE TITLE
Identification NPC art

### ISSUE THREAD

**Issue by dantogno** [dantogno/FishStory#4]
@Cabrill going full deckard cain:
![image](https://user-images.githubusercontent.com/3150710/71754365-7646d580-2e4b-11ea-91e1-53d6c9257aef.png)

**Comment by Cabrill** [comment]
![travelmerchant1_1](https://user-images.githubusercontent.com/2907579/71573613-a2ec9d00-2a99-11ea-9a8b-3f8d570c621c.png)
This one, @dantogno ?  I've added the Idle+Walk Up/Down/Left/Right animation chain as TravelMerchant under NPCs in Glue.  If you want different art, just let me know which one you'd prefer.

**Comment by Cabrill** [comment]
Deckard Cain with cane is now in the game!
