### ISSUE TITLE
Add some sort of animated down arrow when the player needs to click the interact button to advance dialog.

### ISSUE THREAD

**Issue by dantogno** [dantogno/FishStory#41]

**Comment by vchelaru** [comment]
@Cabrill I figured you could tackle this since you may have to put art in the UI sheet, and you know Gum.

**Comment by Cabrill** [comment]
Taking feedback from you both on the bouncing down arrow added if the dialogue is on screen for more than 5 seconds.

**Comment by dantogno** [comment]
@Cabrill Not sure if you saw this but it's in the tileset: 
![image](https://user-images.githubusercontent.com/3150710/71918205-6da21800-3147-11ea-8fc8-4a9b00dd6769.png)

**Comment by dantogno** [comment]
This art would also work well for other UI elements. See #43

**Comment by dantogno** [comment]
Here is a possible font resource: https://w.itch.io/world-of-fonts

**Comment by Cabrill** [comment]
@dantogno I REALLY like those fonts.  Going to use them on https://github.com/dantogno/FishStory/issues/43
