### ISSUE TITLE
Improve UI presentation (font, etc)

### ISSUE THREAD

**Issue by dantogno** [dantogno/FishStory#43]

**Comment by dantogno** [comment]
https://github.com/dantogno/FishStory/issues/43 
This can be used for the dialog box, etc ☝️

**Comment by dantogno** [comment]
@katkeller also mentioned the possibility of making portraits. @Cabrill maybe you can discuss with her if you guys want to try it.

**Comment by Cabrill** [comment]
@katkeller Did you want to try to tackle the task of portraits together?  I can create an NPC frame via Gum using our art assets, and then assign it a rendertarget created in Glue; then what remains is adding a method to link NPC.Name->Pixel(x,y) for the MasterTileSheet to write to that rendertarget when opening dialogue, and manually identifying those x,y values for each NPC with storage in a private read-only dictionary, or something.  Do you think you'll have for any part of that in the next week?  If not, feel free to suggest an alternate approach.

**Comment by Cabrill** [comment]
I just realized that it's a bit simpler than all that, since we already have the X/Y values for NPCs if we just use the top X pixels from the first frame of their idle animation, and don't have to manually identify the values per NPC.
