### ISSUE TITLE
Tycoon Day1 dialog has some apostrophe's that work and some that don't. Any idea what the difference is?

### ISSUE THREAD

**Issue by dantogno** [dantogno/FishStory#71]
@katkeller take a look and if it doesn't seem obvious we can assign this to @Cabrill or @vchelaru.

**Comment by katkeller** [comment]
I figured it out! The ones that weren't working were slightly different than the ones that were (seems like they were serif somehow?) because they had been copy and pasted over from a google doc that I was using for spellcheck.
