### ISSUE TITLE
Sound design

### ISSUE THREAD

**Issue by dantogno** [dantogno/FishStory#76]
Lots of beeps (think Final Fantasy)

- [x] Beep for making menu selections and pressing the button to advance dialog 

- [x] Different tone beep for moving the cursor on menus

- [x] Different tone beep for letters appearing in dialog typewriter effect

**Comment by Cabrill** [comment]
These are in.  Let me know if any/all need to be changed, @dantogno , and also let me know if you want me to try at music.

**Comment by dantogno** [comment]
@Cabrill feel free to try music. Original? I just want to make sure we have something we can use with permission :) I can also ask music composition students if we want, but if creating an original composition interests you, for, go at it!

**Comment by Cabrill** [comment]
@dantogno 
I **could** try an original composition, but I can't guarantee any level of quality.  The music that is currently in the game is courtesy of a free pack from [GameMasterAudio](https://forum.unity.com/threads/released-pro-sound-collection-by-gamemaster-audio.370972/), so if you like it we can keep using it and I have more to select from.
