### ISSUE TITLE
Title menu / screen

### ISSUE THREAD

**Issue by vchelaru** [dantogno/FishStory#82]
Set up the logic and the screen flow, but I don't even know what he name of the game is yet, or how we should deal with the art. 

If you have ideas, feel free to discuss in chat.

**Comment by vchelaru** [comment]
@dantogno Do we have UI for this? If not, I don't know if it's worth spending a ton of time on it.

**Comment by Cabrill** [comment]
I took one pass over this, @dantogno and @katkeller .  Let me know what you think needs to change, or feel free to edit the Underwater.tmx directly if you want to add to the background.  

My other idea for this was to have magic circles flash with light around the fish when they bump into each other, but I kind of like just the simpler fish swimming around once I saw it.  Thoughts?
