### ISSUE TITLE
Q:  How can I change the light radius on the player and adjust brightness?  A:  See Comment.

### ISSUE THREAD

**Issue by Cabrill** [dantogno/FishStory#94]
Change 'LightBrightness' on the PropObject by PropName state (Lantern, Streetlight, etc.) to a value between 0 and 1.  

https://imgur.com/GNwI98Y

If you have a reference to a PropObject in code/script, you can call `.SetBrightness(requestedBrightnessFrom0To1);` on it.

@Cabrill see my comment below

**Comment by dantogno** [comment]
@Cabrill it seems like this changes the brightness only--is it feasible to change the radius of the light circle itself?

**Comment by Cabrill** [comment]
@dantogno 

You can now set the NormalizedLightRadius (0.01-2) on each of the objects, in addition to the brightness.

https://files.gitter.im/vchelaru/StoryMonthly/HXsy/image.png

**Comment by dantogno** [comment]
I like how you have adjusted it as well!
