### ISSUE TITLE
Add props and randomize terrain variants

### ISSUE THREAD

**Issue by Cabrill** [dantogno/FishStory#95]
Need a list of props to be added:

Torch?
Chest?
Flowers?

Also specify any functionality the prop should have that necessitates a prop object, and not just a Tile with collision, or conversable NPC so I can implement it.

**Comment by dantogno** [comment]
@Cabrill I was just thinking visual variation and non-interactive props (though some may need collision added). For example, bushes, flowers, trees, variant versions of grass / dirt / pavement tiles peppered in, etc.  

So in other words, just stuff to directly paint in the tmx.
