### ISSUE TITLE
Should the fish go bad and not sell to the fishmonger if it's not sold the day of catching it?

### ISSUE THREAD

**Issue by dantogno** [dantogno/FishStory#97]
Maybe it just has a notification the next morning and is auto removed from the inventory?

**Comment by Cabrill** [comment]
@dantogno I added logic to make anything with "fish" in the name (but not "fishing") go bad upon the next day, with a notification.  I also added a toggle to disable it in Debugging variables.  If you decide you don't want it it will be easy to disable.

**Comment by dantogno** [comment]
@Cabrill awesome, thanks! I updated the logic a bit to use a column in the Item csv, since we actually had it already :)
